public enum Level
{
    EMPTY,
    PLAYER_START_POINT,
    GROUND,
    WATER,
    STAR,
    COIN,

    // Block types
    BRICK_BLOCK,
    QUESTION_MARK_BLOCK,
    EXCLAMATION_RED_BLOCK,
    EXCLAMATION_GREEN_BLOCK,
    EXCLAMATION_BLUE_BLOCK
}
